### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [Pustelto/shell_theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by Pustelto** [comment]
Hi @unixorn , thanks for opening an issues and sorry for late response. Will update ASAP.

**Comment by unixorn** [comment]
Please also add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one.

**Comment by Pustelto** [comment]
Done, let me know if you need something more (I was a bit lazy with README.md, but there really isn't much to set).

**Comment by unixorn** [comment]
Is it ok to just call the theme pustelto or would you prefer something else?

**Comment by Pustelto** [comment]
Pustelto theme is fine I suppose. Don't have any catchy name in mind right now 😄
